/**
 * Class-record .xlsx — export, and two ways to import:
 *
 *   1. "Strict" — a file this app exported (optionally edited in Excel).
 *      Fixed layout, see below. Lossless.
 *   2. "Legacy" — a hand-built school grade sheet (e.g. the client's own
 *      historical template) that was never generated by this app. There is
 *      no fixed layout to rely on, so it's detected from its *formulas*:
 *      a transmuted-percentage formula, a weighted-score formula, and a
 *      final-grade average, which is how these sheets are actually built.
 *      Best-effort — every result carries `warnings` and the caller should
 *      show them before anything is written.
 *
 * Export layout:
 *   A1..A9      code / name / semester / school year / schedule / set /
 *               course & year / instructor / program chair
 *   row 11      PERIOD label (PRELIMS / MIDTERMS / FINALS), merged per block
 *   row 12      category name, merged across that category's columns
 *   row 13      assignment name, one per raw-score column
 *   row 14      assignment date (blank if none)
 *   row 15      max points per raw column; weight (decimal) in each Wtd column
 *   row 16+     one student per row, name in column A
 *
 * Per category:  raw₁…rawₙ → Total (=SUM) → % → Wtd (=% × weight)
 *   %  = Total * 50 / (Σ max of the cells the student actually has) + 50
 * Period grade  = Σ of that period's Wtd columns
 * Final grade   = (Prelim + Midterm + Final) / 3
 * All computed cells are live Excel formulas; on import they're ignored and the
 * app recomputes. Re-import does not recover the "excused" flag (excused cells
 * export blank, and blank imports as "not graded yet").
 */
import ExcelJS from 'exceljs/dist/exceljs.min.js';
import { TERMS, TERM_LABELS } from './state.js';
import { uid } from './utils.js';

// A1..A9, in order. semester label / school year come from the subject's
// semester (rows 3-4); the rest from subject.course.
function courseBlockValues(subject, semester) {
  const c = subject.course;
  const sem = semester || {};
  return [
    c.code, c.name, sem.label || '', sem.schoolYear || '',
    c.schedule, c.set, c.courseYear, c.instructor, c.programChair
  ];
}

const R_PERIOD = 11;
const R_CATEGORY = 12;
const R_NAME = 13;
const R_DATE = 14;
const R_MAXWT = 15;
const R_STU = 16;

function colLetter(n) {
  let s = '';
  while (n > 0) {
    const m = (n - 1) % 26;
    s = String.fromCharCode(65 + m) + s;
    n = (n - m - 1) / 26;
  }
  return s;
}

function colNum(s) {
  let n = 0;
  for (const ch of s.toUpperCase()) n = n * 26 + (ch.charCodeAt(0) - 64);
  return n;
}

/* ------------------------------------------------------------------ export */

export async function buildClassRecordBlob(subject, semester) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'Gradebook';
  wb.calcProperties.fullCalcOnLoad = true;

  const ws = wb.addWorksheet('Class Record', {
    views: [{ state: 'frozen', xSplit: 1, ySplit: R_MAXWT }]
  });

  courseBlockValues(subject, semester).forEach((v, i) => {
    const cell = ws.getCell(i + 1, 1);
    cell.value = v || '';
    cell.font = { bold: i < 2 };
  });

  ws.getCell(R_MAXWT, 1).value = 'STUDENT';
  ws.getColumn(1).width = 26;

  const students = subject.students;
  const lastRow = R_STU + Math.max(students.length, 1) - 1;
  students.forEach((s, i) => { ws.getCell(R_STU + i, 1).value = s.name; });

  let col = 2;
  const periodGradeCols = [];

  for (const termKey of TERMS) {
    const term = subject.terms[termKey];
    const periodStart = col;
    const cats = term.categories.filter(c => term.assignments.some(a => a.categoryId === c.id));
    const weightedCols = [];

    for (const cat of cats) {
      const catAssigns = term.assignments.filter(a => a.categoryId === cat.id);
      const rawStart = col;
      for (const a of catAssigns) {
        ws.getCell(R_NAME, col).value = a.name;
        if (a.date) ws.getCell(R_DATE, col).value = a.date;
        ws.getCell(R_MAXWT, col).value = Number(a.max);
        students.forEach((s, i) => {
          const e = subject.scores[s.id + '_' + a.id];
          if (e && !e.excused && e.score !== null && e.score !== undefined) {
            ws.getCell(R_STU + i, col).value = Number(e.score);
          }
        });
        col++;
      }
      const rawStartL = colLetter(rawStart);
      const rawEndL = colLetter(col - 1);

      const totalCol = col++;
      const pctCol = col++;
      const wtCol = col++;
      const totalL = colLetter(totalCol);
      const pctL = colLetter(pctCol);
      const wtL = colLetter(wtCol);

      ws.getCell(R_NAME, totalCol).value = 'Total';
      ws.getCell(R_NAME, pctCol).value = '%';
      ws.getCell(R_NAME, wtCol).value = 'Wtd';
      const wtCell = ws.getCell(R_MAXWT, wtCol);
      wtCell.value = Number(cat.weight) / 100;
      wtCell.numFmt = '0.00';
      weightedCols.push(wtL);

      ws.mergeCells(R_CATEGORY, rawStart, R_CATEGORY, wtCol);
      ws.getCell(R_CATEGORY, rawStart).value = cat.name;

      for (let r = R_STU; r <= lastRow; r++) {
        const countedMax =
          `SUMPRODUCT((${rawStartL}${r}:${rawEndL}${r}<>"")*($${rawStartL}$${R_MAXWT}:$${rawEndL}$${R_MAXWT}))`;
        ws.getCell(r, totalCol).value = { formula: `SUM(${rawStartL}${r}:${rawEndL}${r})` };
        ws.getCell(r, pctCol).value = {
          formula: `IF(${countedMax}=0,"",${totalL}${r}*50/${countedMax}+50)`
        };
        ws.getCell(r, wtCol).value = {
          formula: `IF(${pctL}${r}="","",${pctL}${r}*$${wtL}$${R_MAXWT})`
        };
        ws.getCell(r, pctCol).numFmt = '0.00';
        ws.getCell(r, wtCol).numFmt = '0.00';
      }
    }

    const pgCol = col++;
    const pgL = colLetter(pgCol);
    ws.getCell(R_NAME, pgCol).value = `${TERM_LABELS[termKey].toUpperCase()} GRADE`;
    for (let r = R_STU; r <= lastRow; r++) {
      const cell = ws.getCell(r, pgCol);
      cell.value = weightedCols.length
        ? { formula: weightedCols.map(l => `${l}${r}`).join('+') }
        : null;
      cell.numFmt = '0.00';
    }
    periodGradeCols.push(pgL);

    ws.mergeCells(R_PERIOD, periodStart, R_PERIOD, pgCol);
    ws.getCell(R_PERIOD, periodStart).value = TERM_LABELS[termKey].toUpperCase();
  }

  const fgCol = col++;
  const fgL = colLetter(fgCol);
  ws.getCell(R_NAME, fgCol).value = 'FINAL GRADE';
  const [p, m, f] = periodGradeCols;
  for (let r = R_STU; r <= lastRow; r++) {
    const cell = ws.getCell(r, fgCol);
    cell.value = {
      formula: `IF(OR(${p}${r}="",${m}${r}="",${f}${r}=""),"",(${p}${r}+${m}${r}+${f}${r})/3)`
    };
    cell.numFmt = '0.00';
  }

  const ltCol = col++;
  ws.getCell(R_NAME, ltCol).value = 'LETTER';
  for (let r = R_STU; r <= lastRow; r++) {
    ws.getCell(r, ltCol).value = {
      formula: `IF(${fgL}${r}="","",IF(${fgL}${r}>=90,"A",IF(${fgL}${r}>=80,"B",IF(${fgL}${r}>=70,"C",IF(${fgL}${r}>=60,"D","F")))))`
    };
  }

  for (const rr of [R_PERIOD, R_CATEGORY, R_NAME, R_DATE, R_MAXWT]) {
    const row = ws.getRow(rr);
    row.font = { bold: true };
    row.alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
  }

  const buf = await wb.xlsx.writeBuffer();
  return new Blob([buf], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  });
}

/* ------------------------------------------------------------------ shared */

function cellText(ws, r, c) {
  const v = ws.getCell(r, c).value;
  if (v === null || v === undefined) return '';
  if (typeof v === 'object') {
    if (v.result !== undefined && v.result !== null) return String(v.result).trim();
    if (v.text) return String(v.text).trim();
    if (Array.isArray(v.richText)) return v.richText.map(t => t.text).join('').trim();
    return '';
  }
  return String(v).trim();
}

function cellNum(ws, r, c) {
  const v = ws.getCell(r, c).value;
  if (typeof v === 'number') return v;
  if (v && typeof v === 'object' && typeof v.result === 'number') return v.result;
  const n = parseFloat(cellText(ws, r, c));
  return isNaN(n) ? null : n;
}

/** The formula text of a cell (no leading "=", whitespace stripped), or null. */
function formulaOf(ws, r, c) {
  const v = ws.getCell(r, c).value;
  return v && typeof v === 'object' && typeof v.formula === 'string'
    ? v.formula.replace(/\s+/g, '')
    : null;
}

function parseMerges(ws) {
  const raw = ws.model && ws.model.merges ? ws.model.merges : [];
  return raw.map(range => {
    const [a, b] = range.split(':');
    const ma = a.match(/([A-Z]+)(\d+)/);
    const mb = (b || a).match(/([A-Z]+)(\d+)/);
    return {
      left: colNum(ma[1]), top: +ma[2],
      right: colNum(mb[1]), bottom: +mb[2]
    };
  });
}

/** A1..A9, read the same way regardless of which parser is reading them. */
function readCourseBlock(ws) {
  return {
    course: {
      code: cellText(ws, 1, 1),
      name: cellText(ws, 2, 1),
      schedule: cellText(ws, 5, 1),
      set: cellText(ws, 6, 1),
      courseYear: cellText(ws, 7, 1),
      instructor: cellText(ws, 8, 1),
      programChair: cellText(ws, 9, 1)
    },
    semesterHint: { label: cellText(ws, 3, 1), schoolYear: cellText(ws, 4, 1) }
  };
}

/* ------------------------------------------------------------- strict import */

const TERM_BY_LABEL = {
  PRELIM: 'prelims', PRELIMS: 'prelims',
  MIDTERM: 'midterms', MIDTERMS: 'midterms',
  FINAL: 'finals', FINALS: 'finals'
};

/** Parse a sheet this app exported. Returns a subject draft, or null. */
function parseStrictSheet(ws) {
  const { course, semesterHint } = readCourseBlock(ws);

  const students = [];
  for (let r = R_STU; r < R_STU + 5000; r++) {
    const name = cellText(ws, r, 1);
    if (!name) break;
    students.push({ id: uid(), name, sex: '' });
  }

  const merges = parseMerges(ws);
  const mergeAt = (row, col) =>
    merges.find(mg => row >= mg.top && row <= mg.bottom && col >= mg.left && col <= mg.right);

  const terms = {
    prelims: { categories: [], assignments: [] },
    midterms: { categories: [], assignments: [] },
    finals: { categories: [], assignments: [] }
  };
  const scores = {};

  const maxCol = Math.max(ws.actualColumnCount || 0, ws.columnCount || 0, 2) + 4;
  let c = 2;
  while (c <= maxCol) {
    const pm = mergeAt(R_PERIOD, c);
    const labelCol = pm ? pm.left : c;
    const label = cellText(ws, R_PERIOD, labelCol).toUpperCase().replace(/\s*GRADE$/, '').trim();
    const termKey = TERM_BY_LABEL[label];
    if (!termKey) { c++; continue; }
    const periodRight = pm ? pm.right : c;

    let cc = labelCol;
    while (cc <= periodRight) {
      const cm = mergeAt(R_CATEGORY, cc);
      if (!cm) { cc++; continue; } // e.g. the "<PERIOD> GRADE" column has no category merge
      const catName = cellText(ws, R_CATEGORY, cm.left) || 'Category';
      const wtCol = cm.right;                 // block = raw… | Total | % | Wtd
      const rawStart = cm.left;
      const rawEnd = cm.right - 3;
      const weightDec = cellNum(ws, R_MAXWT, wtCol);

      const category = {
        id: uid(),
        name: catName,
        weight: weightDec != null ? Math.round(weightDec * 100) : 0
      };
      terms[termKey].categories.push(category);

      for (let rc = rawStart; rc <= rawEnd; rc++) {
        const assignment = {
          id: uid(),
          name: cellText(ws, R_NAME, rc) || `Item ${rc}`,
          categoryId: category.id,
          max: cellNum(ws, R_MAXWT, rc) || 100,
          date: cellText(ws, R_DATE, rc)
        };
        terms[termKey].assignments.push(assignment);
        students.forEach((s, i) => {
          const val = cellNum(ws, R_STU + i, rc);
          if (val !== null) scores[s.id + '_' + assignment.id] = { score: val, excused: false };
        });
      }
      cc = cm.right + 1;
    }
    c = periodRight + 1;
  }

  const assignmentCount = TERMS.reduce((n, t) => n + terms[t].assignments.length, 0);
  if (!students.length && !assignmentCount) return null;

  return { id: uid(), semesterHint, course, students, terms, scores };
}

/* ------------------------------------------------------------- legacy import */
/*
 * A hand-built sheet has no fixed layout, so it's found from its formulas —
 * these three shapes are how a transmuted-grade class record is actually
 * built, whoever built it (confirmed against the client's real template,
 * which has two sheets that don't even agree with each other on which row
 * holds the weight — this only works because it reads that row out of the
 * formula instead of assuming a fixed one):
 *
 *   %       "<Total><r>*50/$<Total>$<maxRow>+50"     e.g. K12*50/$K$11+50
 *   Wtd     "<%><r>*$<Weight>$<row>"                 e.g. L12*$M$11
 *   Final   "(<pg1>+<pg2>+<pg3>)/3"                  e.g. (CT12+BG12+T12)/3
 * A period grade cell is itself a plain sum of ≥2 single-cell refs, e.g.
 * "S11+P11+M11" — each ref is one category's Wtd column.
 */

const PCT_RE = /^([A-Z]+)(\d+)\*50\/\$([A-Z]+)\$(\d+)\+50$/;
const WTD_RE = /^([A-Z]+)(\d+)\*\$([A-Z]+)\$(\d+)$/;
const FINAL_RE = /^\(([A-Z]+)(\d+)\+([A-Z]+)(\d+)\+([A-Z]+)(\d+)\)\/3$/;
const SUM_REFS_RE = /^[A-Z]+\d+(?:\+[A-Z]+\d+)+$/;

const colOfRef = ref => ref.match(/[A-Z]+/)[0];
const rowOfRef = ref => +ref.match(/\d+/)[0];
const looksLikeDate = t => /^\d{1,2}([/-]\d{1,4}){1,2}$/.test(t);

/** First non-date text in the 1-3 rows above a block's max row, across its columns. */
function findCategoryName(ws, block) {
  for (const r of [block.maxRow - 2, block.maxRow - 3, block.maxRow - 1]) {
    if (r < 1) continue;
    for (let c = block.rawStart; c <= block.wtCol; c++) {
      const t = cellText(ws, r, c);
      if (t && !looksLikeDate(t)) return t;
    }
  }
  return null;
}

/** Every "category block" this sheet's formulas reveal, keyed by weighted column. */
function findLegacyBlocks(ws, maxRowScan, maxColScan) {
  const groups = new Map(); // "pctCol|totalColLetter|maxRow" -> { pctCol, totalCol, maxRow, rows[] }
  for (let r = 1; r <= maxRowScan; r++) {
    for (let c = 1; c <= maxColScan; c++) {
      const f = formulaOf(ws, r, c);
      if (!f) continue;
      const m = f.match(PCT_RE);
      if (!m) continue;
      const [, numCol, numRow, denomCol, denomRow] = m;
      if (numCol !== denomCol || +numRow !== r) continue;
      const key = `${c}|${numCol}|${denomRow}`;
      if (!groups.has(key)) groups.set(key, { pctCol: c, totalCol: colNum(numCol), maxRow: +denomRow, rows: [] });
      groups.get(key).rows.push(r);
    }
  }

  const blocks = [];
  for (const g of groups.values()) {
    // A category with only one raw item has no "Total = SUM(...)" formula at
    // all — the single raw cell doubles as the total. Only categories with 2+
    // items get a real SUM, which is also how we learn their raw column range.
    const sumF = formulaOf(ws, g.maxRow, g.totalCol);
    const sumM = sumF && sumF.match(/^SUM\(([A-Z]+)(\d+):([A-Z]+)(\d+)\)$/);
    let rawStart = g.totalCol;
    let rawEnd = g.totalCol;
    if (sumM && +sumM[2] === g.maxRow && +sumM[4] === g.maxRow) {
      rawStart = colNum(sumM[1]);
      rawEnd = colNum(sumM[3]);
    }

    let wtCol = null;
    let weightRow = null;
    const sampleRow = g.rows[0];
    for (let cc = g.pctCol + 1; cc <= g.pctCol + 3; cc++) {
      const wf = formulaOf(ws, sampleRow, cc);
      const wm = wf && wf.match(WTD_RE);
      if (wm && colNum(wm[1]) === g.pctCol && +wm[2] === sampleRow) {
        wtCol = cc;
        weightRow = +wm[4];
        break;
      }
    }
    if (wtCol == null) continue; // no matching weight formula -> not a usable block

    blocks.push({ ...g, rawStart, rawEnd, wtCol, weightRow });
  }

  blocks.sort((a, b) => a.totalCol - b.totalCol);
  return blocks;
}

/** Up to 3 groups of weighted-column-letters, in Prelim/Midterm/Final order, or null. */
function findLegacyPeriodOrder(ws, maxRowScan, maxColScan, knownWtCols) {
  for (let r = 1; r <= maxRowScan; r++) {
    for (let c = 1; c <= maxColScan; c++) {
      const f = formulaOf(ws, r, c);
      const m = f && f.match(FINAL_RE);
      if (!m) continue;
      const refs = [`${m[1]}${m[2]}`, `${m[3]}${m[4]}`, `${m[5]}${m[6]}`];
      const groups = refs.map(ref => {
        const pf = formulaOf(ws, rowOfRef(ref), colNum(colOfRef(ref)));
        return pf && SUM_REFS_RE.test(pf) ? pf.split('+').map(colOfRef) : null;
      });
      if (groups.every(Boolean)) return groups;
    }
  }

  // Fallback: no "(a+b+c)/3" cell found (e.g. the sheet duplicates a value
  // instead of formula-referencing the period grade) — hunt for up to 3
  // standalone sums of already-known weighted columns instead.
  const found = [];
  for (let r = 1; r <= maxRowScan && found.length < 3; r++) {
    for (let c = 1; c <= maxColScan && found.length < 3; c++) {
      const f = formulaOf(ws, r, c);
      if (!f || !SUM_REFS_RE.test(f)) continue;
      const cols = f.split('+').map(colOfRef);
      if (cols.length >= 2 && cols.every(cl => knownWtCols.has(cl))) found.push(cols);
    }
  }
  return found.length ? found : null;
}

/**
 * Parse a hand-built class record from its formulas. Returns
 * { subject, warnings } or null if this sheet doesn't look like one at all.
 */
function parseLegacySheet(ws) {
  const maxRowScan = Math.max(ws.actualRowCount || 0, ws.rowCount || 0, 2) + 2;
  const maxColScan = Math.max(ws.actualColumnCount || 0, ws.columnCount || 0, 2) + 2;

  const blocks = findLegacyBlocks(ws, maxRowScan, maxColScan);
  if (!blocks.length) return null;

  const knownWtCols = new Set(blocks.map(b => colLetter(b.wtCol)));
  const periodOrder = findLegacyPeriodOrder(ws, maxRowScan, maxColScan, knownWtCols);

  const periodKeys = ['prelims', 'midterms', 'finals'];
  const blockByWtCol = new Map(blocks.map(b => [colLetter(b.wtCol), b]));
  const byPeriod = { prelims: [], midterms: [], finals: [] };
  const used = new Set();
  if (periodOrder) {
    periodOrder.slice(0, 3).forEach((cols, i) => {
      for (const cl of cols) {
        const b = blockByWtCol.get(cl);
        if (b && !used.has(b)) { byPeriod[periodKeys[i]].push(b); used.add(b); }
      }
    });
  }
  const unassigned = blocks.filter(b => !used.has(b));
  if (unassigned.length) byPeriod.prelims.push(...unassigned); // don't silently drop them

  const assignedCount = periodKeys.reduce((n, k) => n + byPeriod[k].length, 0);
  if (!assignedCount) return null;

  // the row most blocks agree is "the max/header row" — sturdier than picking
  // blocks[0] if one or two blocks were anchored to an odd row
  const rowVotes = new Map();
  blocks.forEach(b => rowVotes.set(b.maxRow, (rowVotes.get(b.maxRow) || 0) + 1));
  const anchorMaxRow = [...rowVotes.entries()].sort((a, b) => b[1] - a[1])[0][0];

  // student name column: look for a "NAMES"/"STUDENT" label near that row
  const firstRaw = Math.min(...blocks.map(b => b.rawStart));
  let nameCol = null;
  for (let r = Math.max(1, anchorMaxRow - 2); r <= anchorMaxRow && !nameCol; r++) {
    for (let c = 1; c < firstRaw; c++) {
      if (/^(names?|students?)$/i.test(cellText(ws, r, c))) { nameCol = c; break; }
    }
  }
  if (nameCol == null) nameCol = 1;

  // Student rows, independent of which rows happen to still carry a live
  // formula (real sheets often have formulas only on the first few rows and
  // plain pasted numbers below). Scan the sheet's real extent rather than
  // stopping at the first blank — a blank row can be a dropped student, not
  // the end of the roster.
  const lastPossibleRow = Math.max(
    ws.actualRowCount || 0,
    (ws.dimensions && ws.dimensions.bottom) || 0,
    anchorMaxRow
  ) + 5;
  const studentRows = [];
  for (let r = anchorMaxRow + 1; r <= lastPossibleRow; r++) {
    if (cellText(ws, r, nameCol)) studentRows.push(r);
  }
  if (!studentRows.length) return null;

  const { course, semesterHint } = readCourseBlock(ws);
  const students = studentRows.map(r => ({ id: uid(), name: cellText(ws, r, nameCol), sex: '' }));
  const terms = {
    prelims: { categories: [], assignments: [] },
    midterms: { categories: [], assignments: [] },
    finals: { categories: [], assignments: [] }
  };
  const scores = {};

  for (const key of periodKeys) {
    for (const b of byPeriod[key]) {
      const weightVal = cellNum(ws, b.weightRow, b.wtCol);
      const category = {
        id: uid(),
        name: findCategoryName(ws, b) || `Category ${terms[key].categories.length + 1}`,
        weight: weightVal != null ? Math.round(weightVal * 100) : 0
      };
      terms[key].categories.push(category);

      for (let rc = b.rawStart; rc <= b.rawEnd; rc++) {
        const dateText = cellText(ws, b.maxRow - 1, rc);
        const assignment = {
          id: uid(),
          name: dateText || `Item ${rc - b.rawStart + 1}`,
          categoryId: category.id,
          max: cellNum(ws, b.maxRow, rc) || 100,
          date: looksLikeDate(dateText) ? dateText : ''
        };
        terms[key].assignments.push(assignment);
        studentRows.forEach((r, i) => {
          const val = cellNum(ws, r, rc);
          if (val !== null) scores[`${students[i].id}_${assignment.id}`] = { score: val, excused: false };
        });
      }
    }
  }

  const warnings = [];
  if (unassigned.length) {
    warnings.push(`${unassigned.length} grade component${unassigned.length === 1 ? '' : 's'} couldn't be matched to Prelims/Midterms/Finals — filed under Prelims. Check the categories below.`);
  }
  if (!periodOrder) {
    warnings.push('Could not confirm term grouping from a "final grade" formula — it\'s a best guess. Double-check which categories landed in which term.');
  }
  warnings.push('Read from a spreadsheet this app didn\'t create, by matching its formulas — please spot-check a few students\' scores after importing.');

  return {
    subject: { id: uid(), semesterHint, course, students, terms, scores },
    warnings
  };
}

/* ------------------------------------------------------------------ import */

/**
 * Rebuild one or more subjects from a class-record .xlsx (an ArrayBuffer).
 * Returns an array of { subject, warnings } — one per worksheet that looks
 * like a class record. `warnings` is empty for the app's own export format.
 * Throws if nothing in the file looks like a class record at all.
 */
export async function parseClassRecord(arrayBuffer) {
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(arrayBuffer);
  if (!wb.worksheets.length) throw new Error('The file has no worksheet.');

  const primary = wb.getWorksheet('Class Record') || wb.worksheets[0];
  const strict = parseStrictSheet(primary);
  if (strict) return [{ subject: strict, warnings: [] }];

  const results = [];
  for (const ws of wb.worksheets) {
    const r = parseLegacySheet(ws);
    if (r) results.push(r);
  }
  if (results.length) return results;

  throw new Error(
    "Couldn't read this as a class record. This works for a file this app exported " +
    "(optionally edited in Excel) or a school grade sheet with live grading formulas " +
    "(a transmuted percentage and a final-grade average). A blank template, or one " +
    "with the formulas removed / replaced by typed-in numbers, can't be read this way."
  );
}
